### ISSUE TITLE
Does not work with Localizing Entries \ Multi-Site

### ISSUE THREAD

**Issue by Eduard-iCH** [statamic/collaboration#90]
Localizing Entries  - https://statamic.dev/tips/localizing-entries
Multi-Site - https://statamic.dev/multi-site

When i switch active locale from the right sidebar - "Collaboration" still remain synced with the old one (incorrectly broadcast its values to any current active localization), until i completely reload the page.
![image](https://github.com/statamic/collaboration/assets/33355363/c0275c36-9c4a-4daf-928e-19632f213e8c)

Looks like [editLocalization()](https://github.com/statamic/cms/blob/e8a24fe6a910e54ca3a8f59cedb4b4afd14d0794/resources/js/components/entries/PublishForm.vue#L639C9-L639C25) does not emit any usable events?

**Comment by duncanmcclean** [comment]
We've just released [Collaboration v2.0.0](https://github.com/statamic/collaboration/releases/tag/v2.0.0) with support for Statamic 6.

Given the changes in both Statamic 6 and Collaboration 2, this may no longer be relevant, so I'm going to close this for now. If you're still running into this on v2.0.0, let us know and we can reopen. 👍

**Comment by tao** [comment]
@duncanmcclean its still broken and I don't have permission to re-open the issue. When two users are logged in and one switches to a translation, it now switches all users to the new translation – so that is unworkable for teams collaborating or working on multiple translations of new content at the same time...

**Comment by tao** [comment]
https://github.com/user-attachments/assets/c6b4bd36-3101-4946-8bbc-0e5ad24aa7bb

**Comment by tao** [comment]
I hope you guys can fix it soon, this bug has been open for like over two years... and Official Statamic addons should all work together... like best friends 🤜⚡🤛

**Comment by samalisam-novu** [comment]
@duncanmcclean @jasonvarga 
Just installed Collaboration for the first time and hit this within minutes of testing. Can confirm it reproduces on v2.0.0 with Statamic 6.

It's actually worse than the original report suggests: the stale subscription doesn't just leak presence/visuals, it writes. While the UI shows locale B, the Workspace is still bound to entry.<id>.<localeA> and applies incoming updated whispers straight onto the live container via setFieldValue. If the editor on locale B then saves, locale A's content gets persisted onto B. For Replicator/Bard fields the whole value is replaced, so one side's edits silently destroy the other's. 🫣

From a quick dig, the root cause looks client-side: the broadcast channel entry.{id}.{site} is correctly registered server-side, but PublishForm.editLocalization() swaps values/meta/site in place without unmounting <PublishContainer>. So onMounted/onUnmounted never re-run, neither publish-container-destroyed nor publish-container-created fire, and the Collaboration Workspace keeps its original channelName forever. It's also keyed by container.name in the Manager, so even if events did re-fire there'd be a collision.

A one-liner in core that keys <PublishContainer> by ${reference}.${site} would force a natural remount and fix this for every addon listening on those lifecycle events, not just Collaboration. Alternatively the addon could watch container.site and re-subscribe on change (plus re-key Manager.workspaces to be per-site).

Would love to see this fixed. In its current state it's a meaningful data-loss risk for any multi-site customer. Happy to help with a PR if useful.

**Comment by jasonvarga** [comment]
Sorting it out now. Thanks for the details.
